version: "3"
services:
  glances:
    image: nicolargo/glances:dev
    container_name: glances
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 127.0.0.1:61208:61208
    pid: "host"
    restart: unless-stopped

